### ISSUE TITLE
"Instructions" not present on Canvas

### ISSUE THREAD

**Issue by JuniperRhy** [learn-co-curriculum/phase-1-first-class-functions#3]
Hello! While going through this earlier I noticed that the "instructions" at the end of the ReadMe are not present on the canvas page. It threw me off as I kept failing the tests and was not sure why.
Thank you!

**Comment by ihollander** [comment]
Thanks for raising this issue! The lesson in question has been updated in Canvas for future cohorts, so they'll see the same information that is presently in the Github repo. Those Canvas changes won't be visible to your cohort, so you'll have to look at the instructions for this particular lesson on Github.
